In [130]:
import numpy as np
import torch

In [131]:
data = np.array([1,2,3])

## Initialization

In [132]:
t1 = torch.Tensor(data) #BY COPY
print(t1)
print(t1.dtype)

tensor([1., 2., 3.])
torch.float32


In [133]:
t2 = torch.tensor(data) #BY COPY
print(t2)
print(t2.dtype)

tensor([1, 2, 3])
torch.int64


In [134]:
t3 = torch.as_tensor(data) #BY REFERENCE
print(t3)
print(t3.dtype)

tensor([1, 2, 3])
torch.int64


In [135]:
t4 = torch.from_numpy(data) #BY REFERENCE
print(t4)
print(t4.dtype)

tensor([1, 2, 3])
torch.int64


In [136]:
data[0:] = 0
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])


In [137]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [138]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [139]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [140]:
torch.rand(2,2) * 5

tensor([[1.4896, 1.7055],
        [0.8445, 3.2899]])

## Reshape, Squeeze/Unsqueeze, Flatten

In [141]:
data = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],])
t = torch.tensor(data)

In [142]:
print(t)
print(t.shape)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])
torch.Size([4, 3])


In [143]:
t1 = t.reshape(1,12)
print(t1.shape)

t2 = t1.squeeze()
print(t2.shape)

t3 = t2.unsqueeze(1)  # -2 to 1 (index to insert dimension at)
print(t3.shape)

torch.Size([1, 12])
torch.Size([12])
torch.Size([12, 1])


In [144]:
# FLATTEN
tf = t.reshape(1,-1) # 1 is one of the desired dimensions, -1 automatically figures out the other dimension
tf = tf.squeeze()
print(tf)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])


In [145]:
# ALTERNATE FLATTEN
t.reshape(-1)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

# CNN Input format
## [ BATCH, CHANNELS, HEIGHT, WIDTH ]

## Reduction

In [159]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

t.shape

torch.Size([3, 3])

In [166]:
print(t.max())
print(t.max().item())
print(t.argmax()) # Position after flattening

tensor(9)
9
tensor(8)


In [167]:
t.max(dim=0) # max along axis 1

torch.return_types.max(
values=tensor([7, 8, 9]),
indices=tensor([2, 2, 2]))

In [168]:
t.max(dim=1) # max along axis 2

torch.return_types.max(
values=tensor([3, 6, 9]),
indices=tensor([2, 2, 2]))